FROM oven/bun:1

ENV DATABASE_URL = ${DATABASE_URL}
ENV RABBITMQ_URL = ${RABBITMQ_URL}
ENV OPENAI_API_KEY = ${OPENAI_API_KEY}

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/server ./apps/server

RUN bun install

RUN bun run generate:db

EXPOSE 8000

CMD ["bun", "start:server"]