FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages/db ./packages/db
COPY ./packages/rabbitMQ ./packages/rabbitMQ
COPY ./packages/openAI ./packages/openAI

COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/server ./apps/server

RUN bun install

RUN bun run generate:db

EXPOSE 8000

CMD ["bun", "start:server"]
