name: Continuous Deployment (Scraper Server)
on:
  push:
    branches: [main]
    # Only trigger on changes to the server code
    paths:
      - "apps/server/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker login
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.server
          push: true
          tags: souravbhowal/jobflowai_scraper_server:${{ github.sha }}

      # SSH into the server and pull the image and run the container
      - name: SSH into the server and pull the image and run the container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop $(docker ps -aq) || true
            docker rm -f $(docker ps -aq) || true
            docker rmi -f $(docker images -aq) || true
            docker volume rm -f $(docker volume ls -q) || true
            docker network rm $(docker network ls -q) || true
            docker system prune -a --volumes -f
            docker pull souravbhowal/jobflowai_scraper_server:${{ github.sha }}
            docker run --name jobflowai_scraper_server -d \
                --restart unless-stopped \
                -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
                -e RABBITMQ_URL=${{ secrets.RABBITMQ_URL }} \
                -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                -e REDIS_URL=${{ secrets.REDIS_URL }} \
                -p 8000:8000 \
                souravbhowal/jobflowai_scraper_server:${{ github.sha }}
